// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPiaBj_PMxc4jf6eGFwknFw2avW-GKVv8',
    appId: '1:562317400988:web:7fe20625a98a6263648659',
    messagingSenderId: '562317400988',
    projectId: 'flutter-exam-46950',
    authDomain: 'flutter-exam-46950.firebaseapp.com',
    storageBucket: 'flutter-exam-46950.firebasestorage.app',
    measurementId: 'G-RS24YE75Z1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpBWpIjMisjGcSeRkj6LUV-_Q3MNdke3s',
    appId: '1:562317400988:android:fa14477a6879845c648659',
    messagingSenderId: '562317400988',
    projectId: 'flutter-exam-46950',
    storageBucket: 'flutter-exam-46950.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLA4W6R9HjkgsFxIldWMyP_PGbhgreru8',
    appId: '1:562317400988:ios:b899c3e27e658308648659',
    messagingSenderId: '562317400988',
    projectId: 'flutter-exam-46950',
    storageBucket: 'flutter-exam-46950.firebasestorage.app',
    iosBundleId: 'com.example.shopAppEx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLA4W6R9HjkgsFxIldWMyP_PGbhgreru8',
    appId: '1:562317400988:ios:b899c3e27e658308648659',
    messagingSenderId: '562317400988',
    projectId: 'flutter-exam-46950',
    storageBucket: 'flutter-exam-46950.firebasestorage.app',
    iosBundleId: 'com.example.shopAppEx',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDPiaBj_PMxc4jf6eGFwknFw2avW-GKVv8',
    appId: '1:562317400988:web:0af81872621b8903648659',
    messagingSenderId: '562317400988',
    projectId: 'flutter-exam-46950',
    authDomain: 'flutter-exam-46950.firebaseapp.com',
    storageBucket: 'flutter-exam-46950.firebasestorage.app',
    measurementId: 'G-1D44TWKQ2L',
  );
}
